import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../../_lib/fonts";

export const metadata: Metadata = {
  title: "Blog Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
